### ISSUE TITLE
Change `https://frank2example.frankframework.org/api/mundo` to `https://api.frank2example.frankframework.org/api/mundo`

### ISSUE THREAD

**Issue by philipsens** [frankframework/frank-manual#122]
The API is being exposed from another URL.

**Comment by mhdirkse** [comment]
Ik heb de manual geüpdated. Ik heb getest dat mijn voorbeeld configuratie in de manual het doet met de nieuwe URL. Issue kan wat mij betreft gesloten worden.

**Comment by mhdirkse** [comment]
Ah, is een issue op de manual. Dan close ik hem zelf.
